### PR TITLE
Optee 1.3 arm tf

### PR DESCRIPTION
**Pull request by lackan**
This pull request update ARM-TF to the newest code, and adapt them to run OPTEE-OS.
Have tested on QEMU-V8 and FVP.

### CODE REVIEW

**Comment by jenswikl** [comment]
Once it build and tests OK on Juno I think it's easier just to ask @jforissier to push your  optee_1.3_arm-tf  branch to this repository.

**Comment by jforissier** [comment]
@jenswi-linaro `lackan:optee_1.3_arm-tf` has conflicts with `linaro-swg:optee_paged_armtf_v1.3`. Do you mean we should just force-push and ignore the conflicts?

**Comment by lackan** [comment]
@jforissier As I discussed with @jbech-linaro before, he said we can create a new branch name optee_1.3_arm-tf , but I don't know how to create a new pull request to a non-existent branch. So I compare it with linaro-swg:optee_paged_armtf_v1.3. For your information.

**Comment by jforissier** [comment]
@lackan got it, thanks. Is your branch ready now? Latest commit is 91e55501bce2 ("qemu: fix compile errors"). Should I push this to `linaro-swg:optee_1.3_arm-tf`?
Otherwise let me know when it is ready.

**Comment by jenswikl** [comment]
Let's wait until Juno is OK too.

**Comment by jforissier** [comment]
Sure.

**Comment by lackan** [comment]
@jforissier I'm ok with push this to linaro-swg:optee_1.3_arm-tf or linaro-swg:optee_paged_armtf_v1.3. And it haven't yet tested ok on Juno. I will fix the compile errors on Juno soon and ask Jens for help to test it on Juno. At that time, it will be ready to push.

**Comment by jenswikl** [comment]
We should not modify any of our old branches with this. It seems this is based on the latest ARM-TF as of  2017-06-28, the new branch name should reflect that somehow.

**Comment by lackan** [comment]
@jforissier As for Jens's email, with the newly added patch of Jens, now it also works on Juno.

**Comment by jockebech** [comment]
I tested this just now on FVP where I was using Jeromes 2.5.0-rc1 manifest and then just checked out this branch. Secure side seems OK in the boot, but it seems like it hangs in UEFI ...
```bash
The default boot selection will start in   3 seconds
```
@lackan Is there any other dependency to this branch/PR?

(if I check out our old 1.2 based ARM-TF branch, then it works).

**Comment by lackan** [comment]
@jbech-linaro Yes, we should add a flag like the patch here. https://github.com/lackan/build/commit/cd9eaf04499b684e8876e2b33c3beadc1c9573d4

**Comment by lackan** [comment]
@jbech-linaro In newest ARM-TF code, the default value of GIC driver of FVP now is GICV3, so we have two choices, one is to change UEFI and OPTEE-OS to GICV3, and the other is to set the ARM-TF GIC driver to GICV3-legacy mode. As I discussed with Jens, he said the second choice is the best now, because it had less change.

**Comment by jockebech** [comment]
Thanks @lackan , it worked fine on FVP with that additional patch (xtest -l 15 on FVP takes ~3 hours on my laptop, phew!). Now I'm currently onto testing with QEMU v8. I have some issues, but I'm not sure if that is locally here or not. I believe we should also use legacy GIC3 mode for QEMU too?

**Comment by lackan** [comment]
@jbech-linaro The qemu code in ARM-TF didn't change the default value, so we needn't add any flag about this.

**Comment by jockebech** [comment]
With a working QEMU v8 build (QEMU itself) I've been able to run this successfully using Jerome's 2.5.0-rc1 manifest also. So, I've also verified this on QEMU and FVP now.
`Tested-by: Joakim Bech <joakim.bech@linaro.org>` (QEMU v8, FVP)

**Comment by jforissier** [comment]
Pushed `lackan/optee_1.3_arm-tf` to `linaro-swg/optee_arm-tf_2017-06-22`.

**Comment by jockebech** [comment]
FYI, on **Juno** I've just tested `linaro-swg/optee_arm-tf_2017-06-22` with the 2.5.0-rc1 manifest and no regressions when running xtest.

**Pull request closed without merging**
